// common/components/layout/Footer/index.tsx
import { Box, Container, Divider, Flex, Text } from "@chakra-ui/react";

const Footer = () => {
	return (
		<Box as="footer">
			<Container maxW={"container.md"}>
				<Box>
					<Text as="h4" textAlign="center">
						A little cuteness for Christmas
					</Text>
				</Box>
				<Divider my={2} variant="think" />
				<Flex justifyContent="space-between">
					<Box>
						<Box></Box>
						<Box></Box>
						<Box></Box>
					</Box>
					<Text as="p">Made by Dong Chi Team</Text>
				</Flex>
			</Container>
		</Box>
	);
};

export default Footer;

// components/app/Footer/index.vue
<template>
  <footer>
    <h4 class="text-sm md:text-xl md:text-4xl text-center"> A little cuteness for Christmas</h4>
    <hr />
    <div class="flex flex-row justify-between items-center">
      <div class="flex gap-2 md:gap-8">
        <div class="w-6 h-6 md:w-12 md:h-12"><icons-instagram /></div>
        <div class="w-6 h-6 md:w-12 md:h-12"><icons-linkedin /></div>
        <div class="w-6 h-6 md:w-12 md:h-12"><icons-facebook /></div>
      </div>
      <div class="text-[7px] md:text-xl">Made by Dong Chi Team</div>
    </div>
  </footer>
</template>

<script lang="ts" setup>

</script>

<style>

</style>
