// components/app/Header/index.vue
<template>
  <header id="app-header" class="relative mx-auto w-fit">
    <div id="title" class="hidden md:block text-right text-white">
      <h1>Merry Christmas</h1>
      <span>gift love for u</span>
    </div>

    <div id="title-mobile" class="block md:hidden">
      <Title />
    </div>

    <div id="star"></div>
  </header>
</template>

<script lang="ts" setup>
import Title from './title.vue';
</script>

<style scoped>
  #title {
    padding-right: 34px;
  }

  #title h1 {
    font-family: MC;
    font-size: 183.64px;
    line-height: 183.64px;
  }

  #title span {
    position: relative;
    font-size: 50px;
    line-height: 61.3px;
    
  }
  
  #title span::before, #title span::after {
    content: '';
    position: absolute;
    bottom: 12px;
    padding: 14px;
    border-bottom: 3px solid #fff;
  }

  #title span::before {
    left: calc(-15px - 28px);
  }
  
  #title span::after {
    right:  calc(-15px - 28px);
  }

  #star {
    position: absolute;
    right: 4%;
    top: 17%;
  }

  #star::after {
    content: '';
    display: block;
    background: url(~/assets/icons/star.svg) no-repeat center/contain;
    width: 15px;
    height: 15px;
  }

  @media (min-width: 768px) {
    #star::after {
      width: 42px;
      height: 42px;
    } 
  }
</style>

// common/components/layout/Header/index.tsx
import { Box, Flex, Text } from "@chakra-ui/react";

// import Banner from "./banner.svg";
import Title from "./title.svg";

import Banner from "../../others/Banner";

const pBefore = {
	content: "''",
	bottom: "10px",
	display: "inline-block",
	padding: "14px",
	margin: "0 14px",
	borderBottom: "3px solid #fff",
};

const pAfter = {
	content: "''",
	bottom: "10px",
	display: "inline-block",
	padding: "14px",
	margin: "0 14px",
	borderBottom: "3px solid #fff",
};

const Header = () => {
	return (
		<Box as="header">
			<Flex
				justifyContent={"center"}
				py={{ base: 0, md: 4 }}
				mb={{ base: "1rem", md: "2rem" }}
			>
				<Flex
					flexDirection="column"
					alignItems={"flex-end"}
					display={{ base: "none", md: "flex" }}
				>
					<Text
						className="bling_after"
						position={"relative"}
						as="h1"
						fontFamily={"MC"}
						fontSize={{ base: "8rem", lg: "12rem" }}
						px={{ base: "3rem" }}
						textAlign={"center"}
						_after={{
							content: "''",
							position: "absolute",
							right: "-1.5rem",
							top: "25%",
							backgroundImage: "url(/icons/star-icon.svg)",
							backgroundSize: "contain",
							backgroundRepeat: "no-repeat",
							width: "42px",
							height: "42px",
						}}
					>
						Merry Christmas
					</Text>
					<Text
						_before={pBefore}
						_after={pAfter}
						as="p"
						marginTop={{ base: "0rem", md: "-2rem" }}
						fontSize={{ base: "0.75rem", sm: "1.5rem", lg: "3rem" }}
					>
						gift love for u
					</Text>
				</Flex>
				<Flex width="60%" display={{ base: "flex", md: "none" }}>
					<Title
						width="100%"
						height="100%"
						display={{ base: "block", md: "none" }}
					/>
				</Flex>
			</Flex>
		</Box>
	);
};

export default Header;
