// components/Section/index.vue
<template>
  <section v-bind="$attrs">
    <template v-if="$props.title">
      <div class="flex justify-center mb-5 md:mb-2">
        <h3 class="flex items-center title text-2xl md:text-[68px] leading-[30px] md:leading-[84px]">{{ $props.title }}</h3>
      </div>
    </template>
    <div>
      <slot />
    </div>
  </section>
</template>

<script setup lang="ts">
  const _props = defineProps<{ title?: string }>()
</script>

<style scoped>  
  .title::before,
  .title::after {
    content: '';
    display: inline-block;
		background-image: url('~/assets/icons/star.svg');
		background-size: contain;
		background-repeat: no-repeat;
		width: 16px;
		height: 16px;
  }

  .title::before {
		margin-right: 10px;
  }
  
  .title::after {
		margin-left: 10px;
  }

  @media (min-width: 768px) {
    .title::before, .title::after {
      width: 25px;
      height: 25px;
    }
    
    .title::before {
      margin-right: 1rem;
    }
    
    .title::after {
      margin-left: 1rem;
    }
  }
</style>

// common/components/layout/Section/index.tsx
import { Box, Center, Text } from "@chakra-ui/react";
import { ReactNode } from "react";

interface ISection {
	title: string;
	children: ReactNode;
}

const before = {
	base: {
		content: "''",
		marginRight: "1rem",
		backgroundImage: "url(/icons/star-icon.svg)",
		backgroundSize: "contain",
		backgroundRepeat: "no-repeat",
		width: "16px",
		height: "16px",
	},
	md: {
		marginLeft: "2.75rem",
		width: "25px !important",
		height: "25px !important",
	},
};

const after = {
	base: {
		content: "''",
		marginLeft: "1rem",
		backgroundImage: "url(/icons/star-icon.svg)",
		backgroundSize: "contain",
		backgroundRepeat: "no-repeat",
		width: "16px",
		height: "16px",
	},
	md: {
		marginLeft: "2.75rem",
		width: "25px !important",
		height: "25px !important",
	},
};

const Section = ({ title, children }: ISection) => {
	return (
		<Box as="section" mt={"4rem"}>
			<Center
				as="h3"
				fontSize={{ base: "1.5rem", sm: "3rem", md: "4rem" }}
				mb={{ base: "2rem" }}
				textAlign="center"
				_before={before}
				_after={after}
			>
				{title}
			</Center>
			<Box>{children}</Box>
		</Box>
	);
};

export default Section;
